import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "../../styles/typography.css";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/hooks/AuthContext";
import { StreamingProvider } from "@/hooks/StreamingContext";
import { FavoritesProvider } from "@/hooks/SaveVideoContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <StreamingProvider>
            <FavoritesProvider>
              {children}
              <Toaster />
            </FavoritesProvider>
          </StreamingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
